project_id = "guauobzuxgvkluxwfvxt"

[functions.send-admin-notification]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.notify-new-question]
verify_jwt = false

[functions.chatbot]
verify_jwt = false
